project:
  type: website
  output-dir: docs
  
website:
  title: "nefro-lacardio"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: semana.qmd
        text: Plan semanal
      - href: evaluacion.qmd
        text: Evaluación
      - href: recursos.qmd
        text: Recursos
      - href: faq.qmd
        text: Preguntas frecuentes

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual